name: Daily Kalimati Market Scraper

on:
  # Run on each push to the repository
  push:
    branches:
      - main
      - master
  # Keep the schedule for later
  schedule:
    - cron: '15 6 * * *'  # 12:00 PM Nepal time (6:15 AM UTC)
  workflow_dispatch:  # Allow manual triggering

# Adding this comment to trigger a commit and potentially activate the repository
jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run scraper
        run: |
          python kalimati_scraper.py
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          
      - name: Create workflow log
        run: |
          echo "Workflow ran at: ${{ steps.date.outputs.date }}" > workflow_log.txt
          
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update market data: ${{ steps.date.outputs.date }}"
          file_pattern: 'data/* workflow_log.txt'
          commit_options: '--no-verify'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          create_branch: false 