name: Daily Kalimati Market Scraper

on:
  schedule:
    # Run every 5 minutes for testing (*/5 * * * *)
    # Original schedule: Run at 6:15 AM UTC (12:00 PM Nepal Time, NPT is UTC+5:45) - 15 6 * * *
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual triggering

# Adding this comment to trigger a commit and potentially activate the repository
jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run scraper
        run: |
          python kalimati_scraper.py
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update market data: ${{ steps.date.outputs.date }}"
          git push 